CREATE TABLE IF NOT EXISTS characters (
  id INTEGER PRIMARY KEY,
  name TEXT DEFAULT '',
  st INTEGER DEFAULT 10,
  dx INTEGER DEFAULT 10,
  iq INTEGER DEFAULT 10,
  ht INTEGER DEFAULT 10,
  hp INTEGER DEFAULT 10,
  hp_max INTEGER DEFAULT 10,
  fp INTEGER DEFAULT 10,
  fp_max INTEGER DEFAULT 10,
  total_cp INTEGER DEFAULT 100,
  will INTEGER DEFAULT 10,
  per INTEGER DEFAULT 10,
  skills TEXT DEFAULT '[]',
  advantages TEXT DEFAULT '[]',
  updated_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS messages (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  role TEXT NOT NULL,
  content TEXT NOT NULL,
  ts INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS world (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT DEFAULT '',
  description TEXT DEFAULT ''
);

CREATE TABLE IF NOT EXISTS saved_characters (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL DEFAULT '',
  world_name TEXT DEFAULT '',
  st INTEGER DEFAULT 10,
  dx INTEGER DEFAULT 10,
  iq INTEGER DEFAULT 10,
  ht INTEGER DEFAULT 10,
  hp INTEGER DEFAULT 10,
  hp_max INTEGER DEFAULT 10,
  fp INTEGER DEFAULT 10,
  fp_max INTEGER DEFAULT 10,
  total_cp INTEGER DEFAULT 100,
  will INTEGER DEFAULT 10,
  per INTEGER DEFAULT 10,
  skills TEXT DEFAULT '[]',
  advantages TEXT DEFAULT '[]',
  notes TEXT DEFAULT '',
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now'))
);
