CREATE TABLE IF NOT EXISTS characters (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL DEFAULT '',
  st INTEGER NOT NULL DEFAULT 10,
  dx INTEGER NOT NULL DEFAULT 10,
  iq INTEGER NOT NULL DEFAULT 10,
  ht INTEGER NOT NULL DEFAULT 10,
  hp INTEGER NOT NULL DEFAULT 10,
  hp_max INTEGER NOT NULL DEFAULT 10,
  fp INTEGER NOT NULL DEFAULT 10,
  fp_max INTEGER NOT NULL DEFAULT 10,
  total_cp INTEGER NOT NULL DEFAULT 100,
  will INTEGER NOT NULL DEFAULT 10,
  per INTEGER NOT NULL DEFAULT 10,
  skills TEXT NOT NULL DEFAULT '[]',
  advantages TEXT NOT NULL DEFAULT '[]',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS messages (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  role TEXT NOT NULL,
  content TEXT NOT NULL,
  ts INTEGER NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS world (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL DEFAULT '',
  description TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
